/*
  # Update Sales Metrics Schema

  1. Changes
    - Drop and recreate sales_metrics table with correct column name
    - Add RLS policies
    - Add triggers for updated_at

  2. Security
    - Enable RLS
    - Add policies for authenticated users
*/

DROP TABLE IF EXISTS sales_metrics;

CREATE TABLE sales_metrics (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  metric_type text NOT NULL CHECK (metric_type IN ('daily', 'weekly', 'monthly')),
  target numeric(10,2) NOT NULL DEFAULT 0,
  revenue numeric(10,2) NOT NULL DEFAULT 0,
  estimated_profit numeric(10,2) NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE sales_metrics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to read sales metrics"
  ON sales_metrics
  FOR SELECT
  TO authenticated
  USING (true);

CREATE TRIGGER update_sales_metrics_updated_at
  BEFORE UPDATE ON sales_metrics
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();